import 'dart:convert';

import '../repository.dart';
import '../statement.dart';

class MockRepo implements MonoRepository {
  var jsonString = '''
  [
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 74",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 72",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 70",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 68",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 67",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 66",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 66",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 66",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки 29",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 28",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 27",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 25",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 26",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 25",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 34",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 33",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 33",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 22",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 21",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 21",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 31",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 14",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 12",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 11",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 6",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 4",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 7",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 6",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 5",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "MzUWuLmMP6HH9m1Zc3sCzk8n4n2ebQAhFYk-I_txIg",
        "time": 1680486329,
        "description": "Від: Ілля Кольцов",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 4",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1000,
        "operationAmount": 1000,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 93100,
        "hold": false
    },
    {
        "id": "kDYmL6m6G_bT5QikTy9qec50yt0mtv4AputGaoQ1Tg",
        "time": 1680486022,
        "description": "Від: Катерина Полянська",
        "comment": "попити чай на Золотих ворота і з‘їсти еклер із Ханей з чоловіком своїм 3",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 92100,
        "hold": false
    },
    {
        "id": "4PDWAt-na1xxhTXvKMMUuo-ELZAfroUyO3cw7j2Ogg",
        "time": 1680485549,
        "description": "Від: Катерина Полянська",
        "comment": "хочу в Дісней круіз 2",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 500,
        "operationAmount": 500,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91600,
        "hold": false
    },
    {
        "id": "GI_Z52uvFJ3nqFnbE3U5wsSzRaIg49ZW5bghs9opzA",
        "time": 1680192689,
        "description": "Від: Катерина Полянська",
        "comment": "I_love_you 2",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 300,
        "operationAmount": 300,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 91100,
        "hold": false
    },
    {
        "id": "hJrkUlyUtPAXh2edmtZE7_F96ysxSjfiiv--pZ0X-A",
        "time": 1680176973,
        "description": "Від: Ілля Кольцов",
        "comment": "I_love_you 1",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 88800,
        "operationAmount": 88800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 90800,
        "hold": false
    },
    {
        "id": "MZs4K2-voPhBAC6M_c8EOL5eiBZUewI8P6XwuQ-rQQ",
        "time": 1678845613,
        "description": "З білої картки",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 200,
        "operationAmount": 200,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 2000,
        "hold": false
    },
    {
        "id": "iMViuY8mynCRFfE3YIFsFsUJywbqLd6i2H_FCaFltg",
        "time": 1678845451,
        "description": "Від: Катерина Полянська",
        "comment": "хочу замуж",
        "mcc": 4829,
        "originalMcc": 4829,
        "amount": 1800,
        "operationAmount": 1800,
        "currencyCode": 980,
        "commissionRate": 0,
        "cashbackAmount": 0,
        "balance": 1800,
        "hold": false
    }
]
  ''';

  @override
  Future<Iterable<Statement>> fetchStatements() async {
    List<dynamic> data = jsonDecode(jsonString);
    var result = <Statement>[];
    for (var element in data) {
      result.add(Statement.fromJson(element));
    }
    return result;
  }
}
